import Navbar from "./components/Navbar";

export const metadata = {
  title: "eCommerce-Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head></head>
      <body>
        <Navbar />

        {children}
        <Navbar />

      </body>
    </html>
  );
}
